### ISSUE TITLE
Game not starting properly

### ISSUE THREAD

**Issue by Vianpyro** [CodeNMore/New-Beginner-Java-Game-Programming-Src#3]
**Description of the bug :** 
When the game starts, the window opens but nothing happens afterwards.

**To Reproduce :**
Step to reproduce the behavior:
* Create a Runnable JAR file or the Tile game
* Double clic the Runnable JAR file to launch it

**Expected behavior :**
I expected the game to launch to play it.

**Screenshots :**
Here is the screenshot of the game... An amazing one...
![paper world v_indev-1 0 2019-01-04 15_29_08](https://user-images.githubusercontent.com/10519369/50709466-e868bc80-1035-11e9-8ce2-79beacff55a1.png)

**Environment :**
 - OS: Windows 10

**Comment by Kamicosi** [comment]
The same thing happens to me, been trying to find a fix but have had no success. Makes me wonder why it runs in Eclipse but doesn't run as a runnable JAR?

**Comment by Vianpyro** [comment]
I don't know why, I really am sorry, I also wonder why it runs in Eclipse but doesn't run as a runnable JAR?
I hope CodeNMore's going to do a tutorial soon to help us!

**Comment by Kamicosi** [comment]
I found the solution! What I did was I made sure that the res folder was a source in the build path before I exported it (Tutorial - https://www.youtube.com/watch?v=d02PK8C5EaA), then when I exported the JAR file I put it in a folder along with a copied version of the res folder from the TileGame project and it loaded up just fine :).

**Comment by thxrben** [comment]
Yes, or you can use this here instead:
`return Font.createFont(Font.TRUETYPE_FONT, FontLoader.class.getResourceAsStream(path)).deriveFont(Font.PLAIN, size);` for the Fonts, and 
`	public static String loadFileAsString(String path){
		InputStream stream = Utils.class.getResourceAsStream("/worlds/world1.txt");
		
		return new BufferedReader(new InputStreamReader(stream))
				.lines().collect(Collectors.joining("\n"));
	}`

for the world file, 
and 
`	public static BufferedImage loadImage(String path){
		try {
			return ImageIO.read(ImageLoader.class.getResourceAsStream(path));
		} catch (IOException e) {
			e.printStackTrace();
			System.exit(1);
		}
		return null;
	}
`
for the Images.

You dont need "/res/..." anymore, just use "/texture/image.png" or whatever may be.
This means, you can export it without having any files around!
